// M1 scaffold — the REAL engine client.
//
// Drop-in replacement for StubEngine: it implements the same `Engine` interface
// the canvas depends on, but backed by a live SpacetimeDB instead of a scripted
// timeline. The React component never changes — you only change which engine it
// constructs.
//
// This file is intentionally OUTSIDE the Next build (see tsconfig "exclude":
// ["spacetime"]) so a missing SDK/bindings can't break `npm run build`. To
// activate it in M1:
//
//   1. npm i @clockworklabs/spacetimedb-sdk
//   2. spacetime generate --lang typescript --out-dir spacetime/client/module_bindings
//   3. move this file (+ module_bindings) under app/engine/ and import it from a
//      small factory (see makeEngine() at the bottom).
//
// The reducer + subscription names below match spacetime/src/lib.rs exactly.

// --- these imports resolve once step 1 + 2 above are done ---
import { DbConnection } from "./module_bindings";        // generated by `spacetime generate`
import type {
  Run, Frame as DbFrame, Verdict as DbVerdict,
} from "./module_bindings";

// The shared contract types. In M1 these come from app/engine/engine.ts; kept
// local here so the scaffold is self-contained.
type NodeState = "seed" | "pro" | "amplify" | "neutral" | "stall" | "idle";
type BudgetTier = "quick" | "standard" | "deep";
type RunStatus =
  | "queued" | "claimed" | "building_graph" | "simulating" | "summarizing" | "done" | "failed";
interface Frame { step: number; node_ref: string; state: NodeState; said: string; }
interface Verdict { outcome: string; confidence: number; cascade: { text: string; kind: "good" | "bad" | "" }[]; }
interface RunState { runId: number; status: RunStatus; progress: number; }
interface Engine {
  estimateCost(tier: BudgetTier): { tier: BudgetTier; agents: number; usd: number };
  runSimulation(
    tier: BudgetTier,
    onStatus: (s: RunState) => void,
    onFrames: (frames: Frame[]) => void,
    onVerdict: (v: Verdict) => void,
  ): { runId: number; cancel: () => void };
}

const COST: Record<BudgetTier, { agents: number; usd: number }> = {
  quick:    { agents: 40,   usd: 0.4 },
  standard: { agents: 240,  usd: 3.1 },
  deep:     { agents: 2200, usd: 18 },
};

export class SpacetimeEngine implements Engine {
  private conn: DbConnection;
  private scenarioId: bigint;

  /** Construct with an already-connected DbConnection and the scenario to run.
   *  Typically:  const conn = await DbConnection.builder()
   *                .withUri(process.env.NEXT_PUBLIC_SPACETIME_URI!)
   *                .withModuleName("scenario-engine").build(); */
  constructor(conn: DbConnection, scenarioId: bigint) {
    this.conn = conn;
    this.scenarioId = scenarioId;
  }

  estimateCost(tier: BudgetTier) {
    // Same up-front estimate as the stub; the hard cap is enforced in the worker.
    return { tier, agents: COST[tier].agents, usd: COST[tier].usd };
  }

  runSimulation(
    tier: BudgetTier,
    onStatus: (s: RunState) => void,
    onFrames: (frames: Frame[]) => void,
    onVerdict: (v: Verdict) => void,
  ) {
    const db = this.conn.db;
    let runId = 0n;

    // Fire submit_run. The reducer returns nothing; we learn our run_id by
    // watching the `run` table for a new row on this scenario.
    this.conn.reducers.submitRun(this.scenarioId, tier, this.estimateCost(tier).usd);

    const onRunInsert = (_ctx: unknown, row: Run) => {
      if (row.scenarioId !== this.scenarioId) return;
      if (runId === 0n) runId = row.id;      // first new run for this scenario is ours
      if (row.id !== runId) return;
      onStatus({ runId: Number(row.id), status: row.status as RunStatus, progress: row.progress });
    };
    const onRunUpdate = (_ctx: unknown, _old: Run, row: Run) => {
      if (row.id !== runId) return;
      onStatus({ runId: Number(row.id), status: row.status as RunStatus, progress: row.progress });
    };
    const onFrameInsert = (_ctx: unknown, row: DbFrame) => {
      if (row.runId !== runId) return;
      onFrames([{ step: row.step, node_ref: row.nodeRef, state: row.state as NodeState, said: row.said }]);
    };
    const onVerdictInsert = (_ctx: unknown, row: DbVerdict) => {
      if (row.runId !== runId) return;
      onVerdict({
        outcome: row.outcome,
        confidence: row.confidence,
        cascade: JSON.parse(row.cascadeJson) as Verdict["cascade"],
      });
    };

    db.run.onInsert(onRunInsert);
    db.run.onUpdate(onRunUpdate);
    db.frame.onInsert(onFrameInsert);
    db.verdict.onInsert(onVerdictInsert);

    // Subscribe so the callbacks receive rows. Mirrors the queries in the README.
    const sub = this.conn
      .subscriptionBuilder()
      .subscribe([
        `SELECT * FROM run     WHERE scenario_id = ${this.scenarioId}`,
        `SELECT * FROM frame   WHERE run_id IN (SELECT id FROM run WHERE scenario_id = ${this.scenarioId})`,
        `SELECT * FROM verdict WHERE run_id IN (SELECT id FROM run WHERE scenario_id = ${this.scenarioId})`,
      ]);

    const cancel = () => {
      db.run.removeOnInsert(onRunInsert);
      db.run.removeOnUpdate(onRunUpdate);
      db.frame.removeOnInsert(onFrameInsert);
      db.verdict.removeOnInsert(onVerdictInsert);
      sub.unsubscribe();
    };

    return { runId: Number(runId), cancel };
  }
}

// M1 wiring: a factory so the component picks an engine from config without
// caring which one it gets.
//
//   export function makeEngine(conn, scenarioId) {
//     return process.env.NEXT_PUBLIC_SPACETIME_URI
//       ? new SpacetimeEngine(conn, scenarioId)
//       : new StubEngine();
//   }
